create database db_usuario
use db_usuario

create table TBL_USUARIO(
	ID_USUARIO BIGINT NOT NULL PRIMARY KEY IDENTITY,
	TX_NOME VARCHAR(20) NOT NULL,
	TX_SENHA VARCHAR(25) NOT NULL,
	NR_TENTATIVAS_ACESSO INT NOT NULL,
	DT_DATA_BLOQUEIO DATETIME NOT NULL,
	DT_DATA_INATIVACAO DATETIME NOT NULL,
	TX_STATUS VARCHAR(20) NOT NULL
);	

create table TBL_PERMISSAO(
ID_PERMISSAO BIGINT PRIMARY KEY,
TX_AUTHORITY VARCHAR(35) NOT NULL
);

create table TBL_USUARIO_PERMISSAO(
ID_USUARIO BIGINT NOT NULL,
ID_PERMISSAO BIGINT,
FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO(ID_USUARIO),
FOREIGN KEY (ID_PERMISSAO) REFERENCES TBL_PERMISSAO(ID_PERMISSAO)
);

